"""Widget layer for the ColabSeqDisplay notebooks.

`theme` is the presentation vocabulary — markdown to HTML, a heading, a note, and
three severities of inline message. `core` is the machinery: a `WizardState`, the
pure functions that decide what is visible and what to warn about, runtime
detection, and the thin ipywidgets wrappers that push those decisions on screen.

A wizard is built from these two and holds no rules of its own.
"""

from __future__ import annotations

from colabsd.ui import theme
from colabsd.ui.core import (
    COLAB_SESSION_MINUTES,
    DEFAULT_WORK_DIR,
    DRIVE_NOTE,
    ESMFOLD_FALLBACK_LENGTH,
    FIELD_KEYS,
    FIELD_RULES,
    FIELD_SECTIONS,
    FREE_T4_MEMORY_GB,
    GPU_TIERS,
    L4_MEMORY_GB,
    MODES,
    PERSISTENCE_MINUTES,
    REFERENCE_LIBRARY_VARIANTS,
    SECTION_ORDER,
    SECTION_TITLES,
    THREE_DI_SOURCES,
    ConfigStatus,
    DriveMount,
    FieldRule,
    Message,
    MessageBoard,
    Plan,
    Predicate,
    Runtime,
    RuntimeEstimate,
    Section,
    WizardState,
    apply_field_visibility,
    apply_visibility,
    backbone_choices,
    backbone_entry,
    backbone_fit,
    backbone_label,
    backbone_messages,
    backbone_summary,
    bind,
    bind_all,
    colab_backbones,
    config_messages,
    config_status,
    detect_runtime,
    drive_env,
    drive_folder_name,
    drive_paths,
    drive_widgets,
    esmfold_safe_length,
    estimate_runtime,
    field_visibility,
    format_minutes,
    gpu_tier,
    has_three_di,
    messages_for,
    mount_drive,
    n_runs,
    needs_structure,
    on_click,
    persistence_messages,
    plan,
    pooling_choices,
    reference_library_variants,
    refresh,
    render_messages,
    reproducibility_messages,
    run_guarded,
    runtime_messages,
    runtime_summary,
    schedule_messages,
    sequence_only_backbones,
    set_display,
    structure_backbones,
    structure_messages,
    t4_class,
    test_unlock_messages,
    visible_fields,
    visible_sections,
)

#: Every public name `colabsd.ui.core` defines, so a wizard can import the whole
#: vocabulary from the package. Keep it in step with `core`, so that a new rule or
#: helper cannot be added there and quietly left unreachable here.
__all__ = [
    "DEFAULT_WORK_DIR",
    "apply_field_visibility",
    "apply_visibility",
    "backbone_choices",
    "backbone_entry",
    "backbone_fit",
    "backbone_label",
    "backbone_messages",
    "backbone_summary",
    "bind",
    "bind_all",
    "colab_backbones",
    "COLAB_SESSION_MINUTES",
    "config_messages",
    "config_status",
    "ConfigStatus",
    "detect_runtime",
    "drive_env",
    "drive_folder_name",
    "DRIVE_NOTE",
    "drive_paths",
    "drive_widgets",
    "DriveMount",
    "ESMFOLD_FALLBACK_LENGTH",
    "esmfold_safe_length",
    "estimate_runtime",
    "FIELD_KEYS",
    "FIELD_RULES",
    "FIELD_SECTIONS",
    "field_visibility",
    "FieldRule",
    "format_minutes",
    "FREE_T4_MEMORY_GB",
    "gpu_tier",
    "GPU_TIERS",
    "has_three_di",
    "L4_MEMORY_GB",
    "Message",
    "MessageBoard",
    "messages_for",
    "MODES",
    "mount_drive",
    "n_runs",
    "needs_structure",
    "on_click",
    "persistence_messages",
    "PERSISTENCE_MINUTES",
    "Predicate",
    "Plan",
    "plan",
    "pooling_choices",
    "REFERENCE_LIBRARY_VARIANTS",
    "reference_library_variants",
    "refresh",
    "render_messages",
    "reproducibility_messages",
    "run_guarded",
    "Runtime",
    "runtime_messages",
    "runtime_summary",
    "RuntimeEstimate",
    "schedule_messages",
    "Section",
    "SECTION_ORDER",
    "SECTION_TITLES",
    "sequence_only_backbones",
    "set_display",
    "structure_backbones",
    "structure_messages",
    "t4_class",
    "test_unlock_messages",
    "theme",
    "THREE_DI_SOURCES",
    "visible_fields",
    "visible_sections",
    "WizardState",
]
